### ISSUE TITLE
Deprecate this package

### ISSUE THREAD

**Issue by ritikbanger** [MahdiMhqq/react18-otp-input#1]
@MahdiMhqq the fork you have taken has only one change that is it resolve the peer dependency issue that the original react otp input has.

But there are so many other bugs and issues pending in this package.

I have resolved all of the bugs and issues that were present in the original one and publish the package with the name [react18-input-otp](https://npmjs.com/package/react18-input-otp) .

It would be great if you mark your fork as deprecated/unpublish it and redirect users to the better one.

Thanks

**Comment by ritikbanger** [comment]
Any update @MahdiMhqq

**Comment by MahdiMhqq** [comment]
Hi dear Ratik
Sorry for delay, been busy with projects 😁.

I saw your repo, but i couldn't find list of bugs/improvements you resolved. Please provide one to me. I check it out and we talk about it more

Cheers 🍻

**Comment by ritikbanger** [comment]
There are over 40 bugs/issues that I have resolved, To name a few:

- React peer dependency issue
- Custom tests and attributes issue
- Unique id issue
- Custom arialabel and over riding issue
- Need of custom input props issue
- Clipboard paste issue on iOS chrome
- Android paste issues
- Keydown issue (enter not working)
- onSubmit prop missing
- Not focusing on 1st input box
- Introduction of separate After to use this a phone number inputs too.

**Comment by ritikbanger** [comment]
Any update?

**Comment by ritikbanger** [comment]
It would be great if you mark your fork as deprecated/unpublish it and redirect users to the better one.

**Comment by MahdiMhqq** [comment]
Okay,
I was planning to add the WebOTP api to this package.
But this days i'm super busy and couldn't make time for this...
If you add this feature to your fork i will deprecate this package.

More info : [WebOTP API](https://web.dev/web-otp/)

**Comment by MahdiMhqq** [comment]
Any Update? @ritikbanger
